import { readFileSync, writeFileSync, existsSync, readdirSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { parseFrontmatter, upsertFrontmatterField } from '../utils/frontmatter.js';
import { getTodayDate } from '../utils/date.js';
import { ARTICLES_BASE_DIR, SUPPORTED_LOCALES, DEFAULT_LOCALE } from '../config/constants.js';

// ---------------------------------------------------------------------------
// 型定義
// ---------------------------------------------------------------------------

type SupportedLocale = (typeof SUPPORTED_LOCALES)[number];

interface TranslationResult {
  title: string;
  summary: string;
  tags: string[];
  body: string;
}

interface TranslateStats {
  total: number;
  translated: number;
  skipped: number;
  errors: number;
}

// ---------------------------------------------------------------------------
// 定数
// ---------------------------------------------------------------------------

const TRANSLATE_MODEL_CLAUDE = 'claude-haiku-4-5-20251001';
const TRANSLATE_MODEL_GEMINI = 'gemini-2.5-flash-lite';
const TRANSLATE_MODEL_OPENAI = 'gpt-4.1-nano';

/** 各言語の自動生成注意文 */
const DISCLAIMER_BY_LOCALE: Record<SupportedLocale, string> = {
  ja: '本記事は LLM により自動生成されたものです。内容に誤りが含まれる可能性があります。',
  en: 'This article was automatically generated by LLM. It may contain errors.',
  zh: '本文由 LLM 自动生成，内容可能存在错误。',
  es: 'Este artículo fue generado automáticamente por LLM. Puede contener errores.',
  pt: 'Este artigo foi gerado automaticamente por LLM. Pode conter erros.',
  fr: "Cet article a été généré automatiquement par LLM. Il peut contenir des erreurs.",
};

/** 各言語の表示名（LLM に渡す） */
const LANGUAGE_NAME_BY_LOCALE: Record<SupportedLocale, string> = {
  ja: 'Japanese',
  en: 'English',
  zh: 'Simplified Chinese',
  es: 'Spanish',
  pt: 'Portuguese',
  fr: 'French',
};

// ---------------------------------------------------------------------------
// LLM API 呼び出し
// ---------------------------------------------------------------------------

/**
 * Claude Haiku API を呼び出して翻訳する（最大3回試行）
 */
async function callClaudeApi(prompt: string): Promise<string> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error('ANTHROPIC_API_KEY is not set');

  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      const response = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
          'x-api-key': apiKey,
          'anthropic-version': '2023-06-01',
          'content-type': 'application/json',
        },
        body: JSON.stringify({
          model: TRANSLATE_MODEL_CLAUDE,
          max_tokens: 16384,
          messages: [{ role: 'user', content: prompt }],
        }),
      });

      if (!response.ok) {
        const errorText = await response.text();
        const isRateLimit = response.status === 429;
        if (attempt < 3) {
          const waitMs = isRateLimit ? 60000 : 5000;
          console.log(`Claude API error ${response.status}, retrying in ${waitMs / 1000}s... (attempt ${attempt}/3)`);
          await new Promise((resolve) => setTimeout(resolve, waitMs));
          continue;
        }
        throw new Error(`Claude API error ${response.status}: ${errorText}`);
      }

      const data = (await response.json()) as {
        content: Array<{ type: string; text?: string }>;
      };
      const textBlock = data.content.find((c) => c.type === 'text' && c.text);
      if (!textBlock?.text) throw new Error('No text content in Claude response');
      return textBlock.text;
    } catch (error) {
      if (attempt < 3) {
        console.log(`Error on attempt ${attempt}: ${error instanceof Error ? error.message : String(error)}, retrying in 5s...`);
        await new Promise((resolve) => setTimeout(resolve, 5000));
      } else {
        throw error;
      }
    }
  }
  throw new Error('Claude API call failed after 3 attempts');
}

/**
 * Gemini Flash Lite API を呼び出して翻訳する（最大3回試行）
 */
async function callGeminiApi(prompt: string): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error('GEMINI_API_KEY is not set');

  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      const url = `https://generativelanguage.googleapis.com/v1beta/models/${TRANSLATE_MODEL_GEMINI}:generateContent?key=${apiKey}`;
      const response = await fetch(url, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({
          contents: [{ role: 'user', parts: [{ text: prompt }] }],
          generationConfig: { maxOutputTokens: 16384 },
        }),
      });

      if (!response.ok) {
        const errorText = await response.text();
        const isRateLimit = response.status === 429;
        if (attempt < 3) {
          const waitMs = isRateLimit ? 60000 : 5000;
          console.log(`Gemini API error ${response.status}, retrying in ${waitMs / 1000}s... (attempt ${attempt}/3)`);
          await new Promise((resolve) => setTimeout(resolve, waitMs));
          continue;
        }
        throw new Error(`Gemini API error ${response.status}: ${errorText}`);
      }

      // response.json() は記事本文の特殊文字で失敗することがあるため
      // response.text() で取得後に手動でパースする
      const rawJson = await response.text();
      let data: { candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }> };
      try {
        data = JSON.parse(rawJson) as typeof data;
      } catch {
        // 不正エスケープ（\: など）をエスケープして再パース
        const fixed = rawJson.replace(/\\(?!["\\/bfnrtu])/g, '\\\\');
        data = JSON.parse(fixed) as typeof data;
      }
      const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
      if (!text) throw new Error('No text content in Gemini response');
      return text;
    } catch (error) {
      if (attempt < 3) {
        console.log(`Error on attempt ${attempt}: ${error instanceof Error ? error.message : String(error)}, retrying in 5s...`);
        await new Promise((resolve) => setTimeout(resolve, 5000));
      } else {
        throw error;
      }
    }
  }
  throw new Error('Gemini API call failed after 3 attempts');
}

/**
 * OpenAI gpt-4.1-nano API を呼び出して翻訳する（最大3回試行）
 */
async function callOpenAiApi(prompt: string): Promise<string> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) throw new Error('OPENAI_API_KEY is not set');

  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      const response = await fetch('https://api.openai.com/v1/chat/completions', {
        method: 'POST',
        headers: {
          authorization: `Bearer ${apiKey}`,
          'content-type': 'application/json',
        },
        body: JSON.stringify({
          model: TRANSLATE_MODEL_OPENAI,
          max_tokens: 16384,
          messages: [{ role: 'user', content: prompt }],
        }),
      });

      if (!response.ok) {
        const errorText = await response.text();
        const isRateLimit = response.status === 429;
        if (attempt < 3) {
          const waitMs = isRateLimit ? 60000 : 5000;
          console.log(`OpenAI API error ${response.status}, retrying in ${waitMs / 1000}s... (attempt ${attempt}/3)`);
          await new Promise((resolve) => setTimeout(resolve, waitMs));
          continue;
        }
        throw new Error(`OpenAI API error ${response.status}: ${errorText}`);
      }

      const data = (await response.json()) as {
        choices?: Array<{ message?: { content?: string } }>;
      };
      const text = data.choices?.[0]?.message?.content;
      if (!text) throw new Error('No text content in OpenAI response');
      return text;
    } catch (error) {
      if (attempt < 3) {
        console.log(`Error on attempt ${attempt}: ${error instanceof Error ? error.message : String(error)}, retrying in 5s...`);
        await new Promise((resolve) => setTimeout(resolve, 5000));
      } else {
        throw error;
      }
    }
  }
  throw new Error('OpenAI API call failed after 3 attempts');
}

/**
 * RESEARCH_PROVIDER に応じて LLM API を呼び出す
 */
async function callTranslateApi(prompt: string, provider: string): Promise<string> {
  switch (provider) {
    case 'claude':
      return callClaudeApi(prompt);
    case 'openai':
      return callOpenAiApi(prompt);
    case 'gemini':
    default:
      return callGeminiApi(prompt);
  }
}

// ---------------------------------------------------------------------------
// 翻訳ロジック
// ---------------------------------------------------------------------------

/**
 * LLM レスポンスから JSON を抽出してパースする
 */
function parseTranslationResponse(rawText: string): TranslationResult {
  let text = rawText.trim();

  // コードフェンスで囲まれている場合は除去
  const fenceMatch = text.match(/^```(?:json)?\s*\n([\s\S]*?)\n```\s*$/);
  if (fenceMatch) {
    text = fenceMatch[1]!.trim();
  }

  // JSON パース（不正エスケープの修正を試みる）
  let parsed: Record<string, unknown>;
  try {
    parsed = JSON.parse(text) as Record<string, unknown>;
  } catch {
    // LLM が JSON 文字列値内に不正なエスケープ（\: など）を含む場合の修復
    const fixed = text.replace(/\\(?!["\\/bfnrtu])/g, '\\\\');
    try {
      parsed = JSON.parse(fixed) as Record<string, unknown>;
    } catch {
      // フォールバック: title, summary, body をキーで手動抽出
      const titleMatch = text.match(/"title"\s*:\s*"((?:[^"\\]|\\.)*)"/);
      const summaryMatch = text.match(/"summary"\s*:\s*"((?:[^"\\]|\\.)*)"/);
      const bodyMatch = text.match(/"body"\s*:\s*"([\s\S]*)"\s*\}?\s*$/);
      if (titleMatch && bodyMatch) {
        parsed = {
          title: titleMatch[1]!.replace(/\\"/g, '"').replace(/\\n/g, '\n'),
          summary: (summaryMatch?.[1] ?? '').replace(/\\"/g, '"').replace(/\\n/g, '\n'),
          body: bodyMatch[1]!.replace(/\\"/g, '"').replace(/\\n/g, '\n'),
        };
      } else {
        throw new Error(`Failed to parse translation response as JSON: ${text.slice(0, 200)}...`);
      }
    }
  }
  const title = typeof parsed.title === 'string' ? parsed.title : '';
  const summary = typeof parsed.summary === 'string' ? parsed.summary : '';
  const tags = Array.isArray(parsed.tags) ? (parsed.tags as unknown[]).map(String) : [];
  const body = typeof parsed.body === 'string' ? parsed.body : '';

  if (!title || !body) {
    throw new Error('Translation response missing required fields (title, body)');
  }

  return { title, summary, tags, body };
}

/**
 * 記事本文から自動生成注意文（`---` 以降の最後のブロック）を除去する
 */
function removeDisclaimerFromBody(body: string): string {
  // 末尾の `---` + 注意文ブロックを除去
  // パターン: \n\n---\n\n> 本記事は... （最後の出現）
  const disclaimerPattern = /\n\n---\n\n>.*$/s;
  return body.replace(disclaimerPattern, '');
}

/**
 * YAML 文字列値を安全にクォートする
 */
function yamlQuote(val: string): string {
  // ダブルクォート内のダブルクォートをエスケープ
  const escaped = val.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return `"${escaped}"`;
}

/**
 * frontmatter の1フィールドを YAML 行に変換する
 */
function formatFrontmatterField(key: string, val: unknown): string {
  if (typeof val === 'boolean') {
    return `${key}: ${val}`;
  }
  if (Array.isArray(val)) {
    return `${key}: ${JSON.stringify(val)}`;
  }
  return `${key}: ${yamlQuote(String(val))}`;
}

/**
 * frontmatter を再構築する（翻訳済み title/summary + 原文の他フィールドをコピー）
 */
function buildTranslatedFrontmatter(
  originalFrontmatter: Record<string, unknown>,
  translatedTitle: string,
  translatedSummary: string,
  translatedTags?: string[],
): string {
  const FIELD_ORDER = ['title', 'slug', 'summary', 'date', 'tags', 'category', 'automated', 'provider', 'sources', 'thumbnail'];

  const merged: Record<string, unknown> = {
    ...originalFrontmatter,
    title: translatedTitle,
    summary: translatedSummary,
    ...(translatedTags && translatedTags.length > 0 ? { tags: translatedTags } : {}),
  };

  const fmLines: string[] = [];

  // FIELD_ORDER に含まれるフィールドを順序通りに出力
  for (const key of FIELD_ORDER) {
    if (merged[key] === undefined) continue;
    if (key === 'provider' && !merged[key]) continue;
    fmLines.push(formatFrontmatterField(key, merged[key]));
  }

  // FIELD_ORDER にないフィールドも末尾に出力
  for (const key of Object.keys(merged)) {
    if (FIELD_ORDER.includes(key)) continue;
    if (key === 'provider' && !merged[key]) continue;
    fmLines.push(formatFrontmatterField(key, merged[key]));
  }

  return `---\n${fmLines.join('\n')}\n---\n`;
}

/**
 * 翻訳プロンプトを構築する
 */
function buildTranslatePrompt(
  targetLocale: SupportedLocale,
  title: string,
  summary: string,
  tags: string[],
  body: string,
): string {
  const promptPath = 'prompts/translate/base.md';
  if (!existsSync(promptPath)) {
    throw new Error(`Translation prompt not found: ${promptPath}`);
  }

  const basePrompt = readFileSync(promptPath, 'utf-8');
  const targetLanguage = LANGUAGE_NAME_BY_LOCALE[targetLocale];

  return basePrompt
    .replace(/\{\{TARGET_LANGUAGE\}\}/g, targetLanguage)
    .replace('{{TITLE}}', title)
    .replace('{{SUMMARY}}', summary)
    .replace('{{TAGS}}', JSON.stringify(tags))
    .replace('{{BODY}}', body);
}

/**
 * 1つの記事を1つの言語に翻訳してファイルに書き出す
 */
async function translateArticle(
  sourceFilePath: string,
  targetLocale: SupportedLocale,
  provider: string,
): Promise<'translated' | 'skipped' | 'error'> {
  // ソースファイルの内容を読み込む
  const sourceContent = readFileSync(sourceFilePath, 'utf-8');
  const { frontmatter, body: fullBody } = parseFrontmatter(sourceContent);

  const title = String(frontmatter.title ?? '');
  const summary = String(frontmatter.summary ?? '');

  // slug: frontmatter から取得。なければファイル名から推定（YYYY-MM-DD-{slug}.md）
  const rawSlug = String(frontmatter.slug ?? '');
  const basename = sourceFilePath.split('/').pop() ?? '';
  const slugFromFilename = basename.replace(/^\d{4}-\d{2}-\d{2}-/, '').replace(/\.md$/, '');
  const slug = rawSlug || slugFromFilename;

  // date: frontmatter から取得。なければファイル名から推定
  const rawDate = String(frontmatter.date ?? '');
  const dateFromFilename = basename.match(/^(\d{4}-\d{2}-\d{2})/)?.[1] ?? '';
  const date = rawDate || dateFromFilename;

  if (!slug || !date) {
    console.warn(`  [${targetLocale}] Missing slug or date in ${sourceFilePath}, skipping`);
    return 'error';
  }

  // 出力パスは元のファイル名をそのまま使用
  const filename = basename;
  const targetDir = join(ARTICLES_BASE_DIR, targetLocale);
  const targetFilePath = join(targetDir, filename);

  // 既存ファイルはスキップ（冪等性）
  if (existsSync(targetFilePath)) {
    console.log(`  [${targetLocale}] Already exists, skipping: ${filename}`);
    return 'skipped';
  }

  // 本文から自動生成注意文を除去（翻訳対象から外す）
  const bodyWithoutDisclaimer = removeDisclaimerFromBody(fullBody);

  // タグを取得
  const tags = Array.isArray(frontmatter.tags) ? (frontmatter.tags as unknown[]).map(String) : [];

  // 翻訳プロンプト構築
  const prompt = buildTranslatePrompt(targetLocale, title, summary, tags, bodyWithoutDisclaimer);

  // LLM API 呼び出し
  console.log(`  [${targetLocale}] Translating via ${provider}...`);
  const rawResponse = await callTranslateApi(prompt, provider);

  // レスポンスをパース
  const translation = parseTranslationResponse(rawResponse);

  // summary の長さを 200 文字に制限
  let translatedSummary = translation.summary;
  if (translatedSummary.length > 200) {
    translatedSummary = translatedSummary.slice(0, 197) + '...';
  }

  // frontmatter 再構築（翻訳されたタグがあればそれを使用、なければ原文タグ）
  const translatedTags = translation.tags.length > 0 ? translation.tags : tags;
  const newFrontmatter = buildTranslatedFrontmatter(frontmatter, translation.title, translatedSummary, translatedTags);

  // 本文 + 対象言語の注意文を組み立て
  const disclaimer = DISCLAIMER_BY_LOCALE[targetLocale];
  const translatedBody = `${translation.body.trim()}\n\n---\n\n> ${disclaimer}\n`;

  const translatedMarkdown = `${newFrontmatter}${translatedBody}`;

  // 出力ディレクトリを作成してファイル書き出し
  mkdirSync(targetDir, { recursive: true });
  writeFileSync(targetFilePath, translatedMarkdown);
  console.log(`  [${targetLocale}] Written: ${filename}`);

  return 'translated';
}

// ---------------------------------------------------------------------------
// ファイル収集
// ---------------------------------------------------------------------------

/**
 * articles/ja/ から対象日付の .md ファイルを収集する
 */
function collectSourceFiles(targetDate: string): string[] {
  const sourceDir = join(ARTICLES_BASE_DIR, DEFAULT_LOCALE);
  if (!existsSync(sourceDir)) return [];

  const files = readdirSync(sourceDir).filter((f) => /^\d{4}-\d{2}-\d{2}-.+\.md$/.test(f));
  return files
    .filter((f) => f.startsWith(targetDate))
    .map((f) => join(sourceDir, f));
}

/**
 * articles/ja/ の全 .md ファイルを収集する（バッチモード）
 */
function collectAllSourceFiles(): string[] {
  const sourceDir = join(ARTICLES_BASE_DIR, DEFAULT_LOCALE);
  if (!existsSync(sourceDir)) return [];

  const files = readdirSync(sourceDir).filter((f) => /^\d{4}-\d{2}-\d{2}-.+\.md$/.test(f));
  return files.map((f) => join(sourceDir, f));
}

// ---------------------------------------------------------------------------
// メイン処理
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  // SKIP_TRANSLATE=true なら即座に終了
  if (process.env.SKIP_TRANSLATE === 'true') {
    console.log('SKIP_TRANSLATE=true, skipping translation.');
    return;
  }

  const provider = process.env.RESEARCH_PROVIDER || 'gemini';
  const isBatchMode = process.env.BATCH_TRANSLATE === 'true';
  const targetDate = getTodayDate();

  // 対象言語を決定（ja は翻訳元なので除外）
  const allTargetLocales = SUPPORTED_LOCALES.filter((l) => l !== DEFAULT_LOCALE) as SupportedLocale[];
  let targetLocales: SupportedLocale[];

  const translateLangsEnv = process.env.TRANSLATE_LANGS;
  if (translateLangsEnv) {
    const requested = translateLangsEnv.split(',').map((l) => l.trim());
    targetLocales = allTargetLocales.filter((l) => requested.includes(l));
    if (targetLocales.length === 0) {
      console.error(`TRANSLATE_LANGS contains no valid locales: ${translateLangsEnv}`);
      console.error(`Valid locales: ${allTargetLocales.join(', ')}`);
      process.exit(1);
    }
  } else {
    targetLocales = allTargetLocales;
  }

  // ソースファイルを収集
  const sourceFiles = isBatchMode
    ? collectAllSourceFiles()
    : collectSourceFiles(targetDate);

  if (sourceFiles.length === 0) {
    if (isBatchMode) {
      console.log('No source articles found in articles/ja/. Nothing to translate.');
    } else {
      console.log(`No articles found for date ${targetDate} in articles/ja/. Nothing to translate.`);
    }
    return;
  }

  console.log(`Mode: ${isBatchMode ? 'batch' : 'daily'}`);
  console.log(`Provider: ${provider}`);
  console.log(`Target locales: ${targetLocales.join(', ')}`);
  console.log(`Source files: ${sourceFiles.length}`);

  const stats: TranslateStats = { total: 0, translated: 0, skipped: 0, errors: 0 };

  for (const sourceFilePath of sourceFiles) {
    const filename = sourceFilePath.split('/').pop() ?? sourceFilePath;
    console.log(`\nProcessing: ${filename}`);

    for (let i = 0; i < targetLocales.length; i++) {
      const targetLocale = targetLocales[i]!;
      stats.total++;

      try {
        const result = await translateArticle(sourceFilePath, targetLocale, provider);
        if (result === 'translated') {
          stats.translated++;
        } else if (result === 'skipped') {
          stats.skipped++;
        } else {
          stats.errors++;
        }
      } catch (error) {
        console.error(`  [${targetLocale}] Error: ${error instanceof Error ? error.message : String(error)}`);
        stats.errors++;
      }

      // レート制限回避: 言語間で 1-2 秒待機（最後の言語の後は待機しない）
      if (i < targetLocales.length - 1) {
        await new Promise((resolve) => setTimeout(resolve, 1500));
      }
    }

    // 複数ファイルのバッチモード時、ファイル間で待機
    if (isBatchMode && sourceFiles.indexOf(sourceFilePath) < sourceFiles.length - 1) {
      console.log('Waiting 3s before next article...');
      await new Promise((resolve) => setTimeout(resolve, 3000));
    }
  }

  // サマリーログ
  console.log('\n--- Translation Summary ---');
  console.log(`Total:      ${stats.total}`);
  console.log(`Translated: ${stats.translated}`);
  console.log(`Skipped:    ${stats.skipped}`);
  console.log(`Errors:     ${stats.errors}`);

  if (stats.errors > 0) {
    console.warn(`\nWarning: ${stats.errors} translation(s) failed.`);
  }
}

main().catch((error) => {
  console.error('Unexpected error:', error);
  process.exit(1);
});
