/** 記事カテゴリ一覧 */
export const DAILY_CATEGORIES = ['ai-tech-daily', 'extended-daily'] as const;
export const WEEKLY_CATEGORIES = ['paper-review', 'extended-paper-review', 'community-trends'] as const;
export const RECAP_CATEGORIES = ['ai-weekly-recap', 'extended-weekly-recap', 'monthly-paper-recap'] as const;
export const CATEGORIES = [...DAILY_CATEGORIES, ...WEEKLY_CATEGORIES, ...RECAP_CATEGORIES] as const;
export type DailyCategory = (typeof DAILY_CATEGORIES)[number];
export type WeeklyCategory = (typeof WEEKLY_CATEGORIES)[number];
export type RecapCategory = (typeof RECAP_CATEGORIES)[number];
export type Category = (typeof CATEGORIES)[number];

/** ディレクトリパス */
export const ARTICLES_DIR = 'articles/ja';
export const ARTICLES_BASE_DIR = 'articles';
export const IMAGES_DIR = 'images';
export const TMP_DIR = '.tmp';

/** i18n */
export const SUPPORTED_LOCALES = ['ja', 'en', 'zh', 'es', 'pt', 'fr'] as const;
export const DEFAULT_LOCALE = 'ja';
export type SupportedLocale = (typeof SUPPORTED_LOCALES)[number];

/** 各言語の表示名 */
export const LANGUAGE_NAME_BY_LOCALE: Record<SupportedLocale, string> = {
  ja: 'Japanese',
  en: 'English',
  zh: 'Simplified Chinese',
  es: 'Spanish',
  pt: 'Portuguese',
  fr: 'French',
};

/** 各言語の自動生成注意文 */
export const DISCLAIMER_BY_LOCALE: Record<SupportedLocale, string> = {
  ja: '本記事は LLM により自動生成されたものです。内容に誤りが含まれる可能性があります。',
  en: 'This article was automatically generated by LLM. It may contain errors.',
  zh: '本文由 LLM 自动生成，内容可能存在错误。',
  es: 'Este artículo fue generado automáticamente por LLM. Puede contener errores.',
  pt: 'Este artigo foi gerado automaticamente por LLM. Pode conter erros.',
  fr: "Cet article a été généré automatiquement par LLM. Il peut contenir des erreurs.",
};

/** Imagen API */
export const IMAGEN_MODEL = 'imagen-4.0-generate-001';

/** Thumbnail prompt generation */
export const THUMBNAIL_PROMPT_MODEL = 'claude-haiku-4-5-20251001';
export const THUMBNAIL_COMMON_CONSTRAINTS = `The cat itself must look like an actual photograph — real fur texture with individual hair strands visible, natural eye reflections and catchlights, realistic ambient lighting with natural shadows. However, the SITUATION must be completely impossible and surreal — a real cat placed in an absurd, fantastical, or physically impossible scenario. The contrast between "photorealistic cat" and "impossible situation" is the core aesthetic. Think: a real cat presiding as judge in a grand courtroom wearing a tiny powdered wig, a real cat conducting a full orchestra of kittens in a concert hall, a real cat standing at a podium giving a graduation speech to an audience of cats. The more impossible and absurd the scenario, the better — as long as the cat looks 100% real.
STRICTLY PROHIBITED: Do NOT include any text, letters, words, numbers, watermarks, logos, or captions anywhere in the image. The image must contain absolutely zero text or writing of any kind. No cartoon or illustrated style for the cat — the cat must be photorealistic even when the situation is insane. No server rooms, no circuit boards, no outer space, no cyberspace, no holograms, no glowing neon UIs, no sci-fi aesthetics.`;

/**
 * カテゴリ別の公開時刻（HH:MM）。
 * 同一日の記事を安定してソートするために使用する。
 * 降順ソート（新しい順）のため、先に表示したいカテゴリほど大きい値を設定。
 */
export const CATEGORY_PUBLISH_TIME: Record<string, string> = {
  // Daily（JST 05:00 生成）
  'ai-tech-daily': '05:30',
  'extended-daily': '05:00',
  // Weekly（JST 18:00 生成）
  'paper-review': '19:00',
  'extended-paper-review': '18:30',
  'community-trends': '18:00',
  // Recap
  'ai-weekly-recap': '13:00',
  'extended-weekly-recap': '12:30',
  'monthly-paper-recap': '12:00',
};

/** デフォルト画像 */
export const DEFAULT_IMAGE_PATH = 'images/defaults/default.png';
